// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scrobbles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertScrobble = `-- name: InsertScrobble :exec
INSERT INTO scrobbles (
    username,
    "trackName",
    "trackMbid",
    "artistName",
    "artistMbid",
    "albumName",
    "albumMbid",
    "scrobbledAt",
    "scrobbledAtUnix",
    year
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertScrobbleParams struct {
	Username        string             `json:"username"`
	TrackName       string             `json:"trackName"`
	TrackMbid       pgtype.Text        `json:"trackMbid"`
	ArtistName      string             `json:"artistName"`
	ArtistMbid      pgtype.Text        `json:"artistMbid"`
	AlbumName       pgtype.Text        `json:"albumName"`
	AlbumMbid       pgtype.Text        `json:"albumMbid"`
	ScrobbledAt     pgtype.Timestamptz `json:"scrobbledAt"`
	ScrobbledAtUnix string             `json:"scrobbledAtUnix"`
	Year            int32              `json:"year"`
}

func (q *Queries) InsertScrobble(ctx context.Context, arg InsertScrobbleParams) error {
	_, err := q.db.Exec(ctx, insertScrobble,
		arg.Username,
		arg.TrackName,
		arg.TrackMbid,
		arg.ArtistName,
		arg.ArtistMbid,
		arg.AlbumName,
		arg.AlbumMbid,
		arg.ScrobbledAt,
		arg.ScrobbledAtUnix,
		arg.Year,
	)
	return err
}
