// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (username, "avatarUrl")
VALUES ($1, $2)
ON CONFLICT (username)
DO UPDATE SET "avatarUrl" = EXCLUDED."avatarUrl"
`

type UpsertUserParams struct {
	Username  string      `json:"username"`
	AvatarUrl pgtype.Text `json:"avatarUrl"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.Username, arg.AvatarUrl)
	return err
}
